name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        platform:
          - platform: linux/amd64
            # target: x86_64-unknown-linux-gnu
          - platform: linux/arm64
            # target: aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      # - uses: actions/checkout@v4
      # - uses: Swatinem/rust-cache@v2
      # - uses: houseabsolute/actions-rust-cross@v0
      #   with:
      #     target: ${{ matrix.platform.target }}
      #     args: "--locked --release"
      #     strip: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          # context: .
          platforms: ${{ matrix.platform.platform }}
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
          build-args: BIN_PATH=target/${{ matrix.platform.target }}/release/p110-exporter
