name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        platform:
          - platform: linux/amd64
            target: x86_64-unknown-linux-gnu
          - platform: linux/arm64
            target: aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: houseabsolute/actions-rust-cross@v0
        with:
            target: ${{ matrix.platform.target }}
            args: "--locked --release"
            strip: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p target/release && cp target/${{ matrix.platform.target }}/release/p110-exporter target/release/p110-exporter
      - uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform.platform }}